version: '3'

services:
  app:
    image: 'frm-boilerplate'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: 'testing'
    environment:
      NODE_APP_INSTANCE: 'docker'
    command: >
      sh -c "make run-lint && make run-vulture && make run-test"
    depends_on:
      - db
    volumes:
      - ./output:/app/output

  db:
    image: mongo:5.0
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
