node:
  config:
    env: 'NODE_CONFIG_ENV'

jwt:
  token: 'JWT_TOKEN'

mongoDb:
  uri: 'MONGODB_URI'

server:
  port: 'PORT'

webAppHost: 'WEB_APP_HOST'

inspectlet:
  wid: 'INSPECTLET_KEY'

papertrail:
  host: 'PAPERTRAIL_HOST'
  port: 'PAPERTRAIL_PORT'
