webAppHost: 'http://localhost:3000'

jwt:
  token: 'dev_auth_token'

logger:
  transports: [ 'console', 'papertrail']

mongoDb:
  uri: 'mongodb+srv://aks97cs:5HCKHGcnIRquGJmd@cluster0.ddn1klz.mongodb.net/?retryWrites=true&w=majority'
  dbName: 'airbnd'
