[tool.black]
line-length = 120
skip-magic-trailing-comma = true
target-version = ['py311']

[tool.isort]
line_length = 120
multi_line_output = 3
profile = "black"
py_version = "311"

[tool.vulture]
exclude = []
ignore_decorators = []
ignore_names = []
min_confidence = 90
paths = [
    "modules",
    "bin",
    "./server.py",
]
sort_by_size = true
